# Generated by Django 3.1.1 on 2020-09-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfname', models.CharField(max_length=50)),
                ('slname', models.CharField(max_length=50)),
                ('semail', models.EmailField(max_length=254, unique=True)),
                ('sregno', models.CharField(max_length=50, unique=True)),
                ('scourse', models.CharField(max_length=50)),
                ('scontact', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
